[project]
name = "newsagent"
version = "0.1.0"
description = "Agentic, multitool claim verification system"
authors = [{ name = "Benjamin Basseri", email = "bbasseri@fas.harvard.edu" }]
dependencies = []


[tool.pytest.ini_options]
pythonpath = [
  "."
]