apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: newsagent
spec:
  selector:
    app: newsagent
    component: api
  ports:
  - port: 8001
    targetPort: 8000
    name: http
  type: ClusterIP
