apiVersion: v1
kind: Service
metadata:
  name: django
  namespace: newsagent
spec:
  selector:
    app: newsagent
    component: django
  ports:
  - port: 8000
    targetPort: 8000
    name: http
  type: ClusterIP
