apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: newsagent
spec:
  selector:
    app: newsagent
    component: mysql
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql
  type: ClusterIP
