apiVersion: v1
kind: Service
metadata:
  name: newsagent-db
  namespace: newsagent
  labels:
    app: newsagent-db
spec:
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql
  selector:
    app: newsagent-db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: newsagent
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: newsagent-db
  namespace: newsagent
  labels:
    app: newsagent-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newsagent-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: newsagent-db
    spec:
      serviceAccountName: newsagent-service-account
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: newsagent-secrets
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: newsagent-config
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: newsagent-config
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: newsagent-secrets
              key: MYSQL_PASSWORD
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "1"
            memory: "2Gi"
      volumes:
      - name: mysql-persistent-storage
        emptyDir: {}
      - name: mysql-initdb
        configMap:
          name: mysql-initdb-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
  namespace: newsagent
data:
  init.sql: |
    -- Create database if not exists
    CREATE DATABASE IF NOT EXISTS fakenews_db;
    USE fakenews_db;
