# Generated by Django 5.1.7 on 2025-03-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_info", "0003_apikey"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertool",
            name="is_preferred",
            field=models.BooleanField(default=False),
        ),
    ]
