apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
  namespace: newsagent
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: newsagent-ebs
