apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: newsagent
type: Opaque
stringData:
  # Database credentials
  DB_PASSWORD: "your-db-password"
  MYSQL_ROOT_PASSWORD: "your-mysql-root-password"
  MYSQL_PASSWORD: "your-mysql-password"
  
  # API keys
  # Note: In a production environment, you would not store actual secrets in YAML files
  # Instead, use a secrets management solution like AWS Secrets Manager, HashiCorp Vault,
  # or Kubernetes Secrets encrypted with sealed-secrets or external-secrets
  WOLFRAM_APP_ID: "your-wolfram-app-id"
  TAVILY_API_KEY: "your-tavily-api-key"
  LANGCHAIN_API_KEY: "your-langchain-api-key"
  OPENAI_API_KEY: "your-openai-api-key"
  
  # AWS credentials
  AWS_ACCESS_KEY_ID: "your-aws-access-key-id"
  AWS_SECRET_ACCESS_KEY: "your-aws-secret-access-key"
  AWS_REGION: "your-aws-region"
  
  # LLM model settings
  CLAIM_DECOMPOSER_MODEL: "mistral-nemo"
  RESEARCH_AGENT_MODEL: "mistral-nemo"
  REASONING_AGENT_MODEL: "mistral-nemo"
  VERDICT_AGENT_MODEL: "mistral-nemo"
