name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - run: |
          touch core/.env
      - name: Run docker compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          services: "api"
      - name: Execute tests in the running services
        run: |
          docker compose exec api python -m pytest tests/